CREATE TABLE  "XXES_INV_ORG_ASSIGNMENTS" 
   (	"ITEM_REQUEST_ID" NUMBER, 
	"ORGANIZATION_CODE" VARCHAR2(3), 
	"ORGANIZATION_ID" NUMBER, 
	"TEMPLATE_NAME" VARCHAR2(30), 
	"TEMPLATE_ID" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_LOGIN" NUMBER
   )
/
