CREATE TABLE  "XXIW_IR_ATTACHMENTS" 
   (	"IR_ATTACHMENT_ID" NUMBER, 
	"ITEM_REQUEST_ID" NUMBER, 
	"FILENAME" VARCHAR2(4000), 
	"FILE_MIMETYPE" VARCHAR2(512), 
	"FILE_CHARSET" VARCHAR2(512), 
	"FILE_BLOB" BLOB, 
	"FILE_COMMENTS" VARCHAR2(4000), 
	"ENABLED_FLAG" VARCHAR2(100), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE
   )
/