CREATE TABLE  "XXIW_ATTRIBUTES" 
   (	"ATTRIBUTE_ID" NUMBER, 
	"NAME" VARCHAR2(150), 
	"DESCRIPTION" VARCHAR2(150), 
	"ENABLED_FLAG" VARCHAR2(10), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE
   )
/
