CREATE TABLE  "XXIW_FLEXFIELDS_LINES" 
   (	"LINE_ID" NUMBER, 
	"HEADER_ID" NUMBER, 
	"SEQ_NUMBER" VARCHAR2(10), 
	"ATTRIBUTE" VARCHAR2(30), 
	"MEANING" VARCHAR2(30), 
	"DESCRIPTION" VARCHAR2(50), 
	"ENABLED_FLAG" VARCHAR2(10), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE
   )
/
