CREATE TABLE  "XXIW_ORG_ASSIGNMENTS" 
   (	"ORG_ASSINMENT_ID" NUMBER, 
	"ITEM_REQUEST_ID" NUMBER, 
	"ORGANIZATION_CODE" VARCHAR2(3), 
	"ORGANIZATION_ID" NUMBER, 
	"TEMPLATE_NAME" VARCHAR2(30), 
	"TEMPLATE_ID" NUMBER, 
	"ENABLED_FLAG" VARCHAR2(10), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE
   )
/
