CREATE TABLE  "XXIW_ATTRIBUTE_ASSOCIATION" 
   (	"ASSOCIATION_ID" NUMBER, 
	"ITEM_CATEGORY" VARCHAR2(150), 
	"PURCHASING_CATEGORY" VARCHAR2(150), 
	"ATTRIBUTE_GROUP" VARCHAR2(150), 
	"ENABLED_FLAG" VARCHAR2(10), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE
   )
/
