CREATE TABLE  "XXIW_LOOKUP_VALUES" 
   (	"LOOKUP_ID" NUMBER, 
	"LOOKUP_TYPE_ID" NUMBER, 
	"LOOKUP_CODE" VARCHAR2(30), 
	"MEANING" VARCHAR2(30), 
	"TAG" VARCHAR2(20), 
	"DESCRIPTION" VARCHAR2(50), 
	"ENABLED_FLAG" VARCHAR2(20), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE
   )
/
