CREATE TABLE  "XXIW_IR_CATEGORIES" 
   (	"IR_CATEGORY_ID" NUMBER, 
	"SEQ_NUMBER" NUMBER, 
	"CATEGORY_NAME" VARCHAR2(30), 
	"ITEM_REQUEST_ID" NUMBER, 
	"ENABLED_FLAG" VARCHAR2(10), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"ORGANIZATION_CODE" VARCHAR2(150), 
	"ORGANIZATION_ID" NUMBER, 
	"CATEGORY_SET_NAME" VARCHAR2(150), 
	"CATEGORY_SET_ID" NUMBER, 
	"CATEGORY_ID" NUMBER
   )
/
