CREATE TABLE  "XXIW_IR_TEMPLATE_SETUPS" 
   (	"TEMPLATE_SETUP_ID" NUMBER, 
	"SETUP_ID" NUMBER, 
	"TEMPLATE_NAME" VARCHAR2(100), 
	"TEMPLATE_ID" NUMBER, 
	"ENABLED_FLAG" VARCHAR2(10), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE
   )
/