CREATE TABLE  "XXIW_IR_COMMENTS" 
   (	"IR_COMMENT_ID" NUMBER, 
	"ITEM_REQUEST_ID" NUMBER, 
	"COMMENTS" VARCHAR2(300), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE
   )
/
