CREATE TABLE  "XXIW_IR_APPROVALS" 
   (	"IR_APPROVAL_ID" NUMBER, 
	"ITEM_REQUEST_ID" NUMBER, 
	"APPROVER_NAME" VARCHAR2(100), 
	"APPROVER_ID" NUMBER, 
	"STATUS" VARCHAR2(20), 
	"COMMENTS" VARCHAR2(150), 
	"ENABLED_FLAG" VARCHAR2(10), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"SUBJECT" VARCHAR2(100)
   )
/