CREATE TABLE  "XXIW_LOOKUP_TYPES" 
   (	"LOOKUP_TYPE_ID" NUMBER, 
	"LOOKUP_TYPE" VARCHAR2(30), 
	"NAME" VARCHAR2(30), 
	"DESCRIPTION" VARCHAR2(40), 
	"ENABLED_FLAG" VARCHAR2(10), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE
   )
/
