CREATE TABLE  "XXIW_IR_UOM_SETUPS" 
   (	"UOM_SETUP_ID" NUMBER, 
	"SETUP_ID" NUMBER, 
	"UOM_NAME" VARCHAR2(100), 
	"UOM_CODE" VARCHAR2(100), 
	"ENABLED_FLAG" VARCHAR2(10), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE
   )
/
