CREATE TABLE  "XXIW_IR_SETUPS" 
   (	"SETUP_ID" NUMBER, 
	"MASTER_ORGANIZATION_ID" NUMBER, 
	"ITEM_NUM_PREFIX" VARCHAR2(10), 
	"DEFUALT_FLAG" VARCHAR2(10), 
	"TEMPLATE_ENABLED" VARCHAR2(10), 
	"UOM_ENABLED" VARCHAR2(10), 
	"ITEM_CATEGORY_ENABLED" VARCHAR2(10), 
	"PO_CATEGORY_ENABLED" VARCHAR2(10), 
	"ENABLED_FLAG" VARCHAR2(10), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"DESCRIPTION_TYPE" VARCHAR2(50), 
	"CATEGORY1_NAME" VARCHAR2(50), 
	"CATEGORY2_NAME" VARCHAR2(50)
   )
/
