CREATE TABLE  "XXIW_APPROVALGRP_LINES" 
   (	"GROUP_LINE_ID" NUMBER, 
	"GROUP_ID" NUMBER, 
	"SEQ_NUMBER" VARCHAR2(10), 
	"EMPLOYEE_ID" NUMBER, 
	"ENABLED_FLAG" VARCHAR2(10), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE
   )
/
