CREATE TABLE  "XXIW_IR_CATEGORIES_SETUPS" 
   (	"CATEGORY_SETUP_ID" NUMBER, 
	"SETUP_ID" NUMBER, 
	"CATEGORY_NAME" VARCHAR2(100), 
	"CATEGORY_ID" NUMBER, 
	"CATEGORY_TYPE" VARCHAR2(30), 
	"ENABLED_FLAG" VARCHAR2(10), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE
   )
/
