CREATE TABLE  "XXIW_FLEXFIELDS_HEADERS" 
   (	"HEADER_ID" NUMBER, 
	"SHORT_NAME" VARCHAR2(30), 
	"NAME" VARCHAR2(30), 
	"DESCRIPTION" VARCHAR2(50), 
	"ENABLED_FLAG" VARCHAR2(10), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE
   )
/
