CREATE TABLE  "XXIW_IR_MPNS" 
   (	"IR_MPN_ID" NUMBER, 
	"SEQ_NUMBER" NUMBER, 
	"MPN_NAME" VARCHAR2(30), 
	"MANUFACTURE_NAME" VARCHAR2(30), 
	"ITEM_REQUEST_ID" NUMBER, 
	"ENABLED_FLAG" VARCHAR2(10), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE
   )
/
