CREATE TABLE  "XXIW_ADMIN_USER" 
   (	"ADMIN_USER_ID" NUMBER, 
	"USER_NAME" VARCHAR2(100), 
	"DESCRIPTION" VARCHAR2(200), 
	"ENABLED_FLAG" VARCHAR2(10), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE
   )
/