CREATE TABLE  "XXIW_APPROVALGRP_HEADERS" 
   (	"GROUP_ID" NUMBER, 
	"GROUP_SHORT_NAME" VARCHAR2(30), 
	"GROUP_NAME" VARCHAR2(30), 
	"DESCRIPTION" VARCHAR2(50), 
	"ENABLED_FLAG" VARCHAR2(10), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE
   )
/